name: "Send Telegram Message"
description: "Sends a message to a Telegram chat with error handling"

inputs:
  bot-token:
    description: "Telegram bot token"
    required: true
  chat-id:
    description: "Telegram chat ID"
    required: true
  message:
    description: "Message text to send"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Telegram message
      shell: bash
      run: |
        set -e

        BOT_TOKEN="${{ secrets.NOTIFICATIONS_BOT_TOKEN }}"
        CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID_MAX }}"
        MESSAGE="${{ github.actor }} test"

        # Send Telegram message
        RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${CHAT_ID}\",
            \"text\": \"${MESSAGE}\"
          }")

        # Check for errors
        OK=$(echo "$RESPONSE" | jq -r '.ok')
        if [ "$OK" != "true" ]; then
          echo "::error::Telegram API call failed: $RESPONSE"
          exit 1
        fi

        echo "✅ Telegram message sent"

