name: "Send Telegram Message"
description: "Sends a message to a Telegram chat with error handling"

inputs:
  bot-token:
    description: "Telegram bot token"
    required: true
  chat-id:
    description: "Telegram chat ID"
    required: true
  message:
    description: "Message text to send"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Telegram message
      shell: bash
      run: ./send-message.sh "${{ inputs.bot-token }}" "${{ inputs.chat-id }}" "${{ inputs.message }}"
